notifications:
  email: ellis.breen@couchbase.com
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686
#  - sudo: required
#    services:
#    - docker
#    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
install:
- docker pull $DOCKER_IMAGE
script:
- ls -alrt
- chmod ugo+x travis/build-wheels.sh
- docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- echo `ls wheelhouse/`
- echo `ls /io/wheelhouse`
- echo `ls .`
- echo `ls /`
- echo `ls /io`
deploy:
  provider: releases
  api_key:
    secure: O8Bs5OoCt/0U0rB5mtUSR8NwK+VvyizB+b4CN91H2MN6+aPBnvIwqoGPihcvu9WY1qT3g/V4JgzNFgppZe4mpzHnM5K9OYrUcH5VQ0kffqQekw6RJu2r7EwjSHdqwlSdevBU5EvL64iJmelgy1qnccm7R5CJFzdi0X7/eWLPOLXRccM9m6cuFwk9cMTtpEIcpia5HIcW+8c+GXDUmFQ2t8AnUMUI+PeNVFAz8rwUAaI0t+ig1VjB2Fi34SFP8K0+CuyaaAJhVP5pdRa7V+MQAAp10Z9ga+brFqEHxsZVvc4yF2o3qOo5Kg3Q+DZLS6O4l3TRN6miQx138Y1ruVCb1L/4cyZ1rQ0IvkQry9VlzE0/v+0Xicc0/lNYZsO6H+0B8lHEUQoirIbCEj7peUakDHxjwNuhDbvSshuJcU6lTHCVt5IBzQb1nwpdruKS60OuURWSmIrU0ayNO9iuekfblYbpbeIUaXLBwV7iY0a+Do89ZJS8nZYRZiZjMEaCoM213b9CEWdIxr8Q44qYFUZ679fCQJc716B1z9Ogcyo6nXaZUfcm4NqjZrBjVm9hPCW6In5fprhlnRWudiK/0Ohc6SaCCK0ZbG6udm2aFqw5QU99WXCiauebxMVJbqaiTBg73EIDMd7LPnRxjIw1hPP0IMnJZ5SChuzG7SUSk0n6Acg=
  file_glob: true
  file: wheelhouse/*
  skip_cleanup: true
  on:
    repo: griels/couchbase-python-client-ng
    all_branches: true
