notifications:
  email: ellis.breen@couchbase.com
language: python
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - $PIP install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse
  - echo `ls wheelhouse/`
deploy:
  provider: releases
  api_key:
    secure: fGIw93WtABD6qcyht+uPQnSPW8RvykJU6GsHq8a+tvP8hxP0+4yYtiGh1OHyIu447qK5tvKrvmyOq6cN/BFO4pE28r9VWidA9nzkT8ug9MPhYAgtw7jb9swunkp8cKXbaVbPokuiS7AUCtAYQV3IJHWU7s3+Me+I8Lgac/15kZ3YsYQ3+ThA6DWNf1lVSjmUcnC2zEBbXaV6pFfffY3R0DpL15inVydpnzXbksgAOTDneppvHXKvt00XmAiZzUlmX8STdh20aav25NJBCCB2WhRpe924x56VVrprsVNuCzzWWAuN9vOnIfuyYLi6Dgfuz+4tKzJlFHxd9MEVfCoD16F1bxdWWTrPHeyvdckHg9sE5D8NvxqfcRkVpJYT6sq54kDbYOil4bPJmFmwR0RzBNXhUODAYl3iM+4W/ukwFBH6cLOCzVq9fkWM2gEroMi4KABvSmgTjeWODN4qEvoraVwdR67cYJzVGcrzZwPZbrXuaeLUrh7fh/ji3YZ6x5vV/9ZwRn5fy+rIm+40E4BSs35oVTGPhYlZOtWSCkCB0erXm1oTdA5ZKezcEpepn7LKcPpnqyR1s2i1Ycux1ztapy+dElLi1O4GT+YNnhwwoPc5r5G34iRxhg+w7g8peHHd9y40AJ6pQ1eaYFk2ZsvU+glDhY41SxkjSFXRNg8DcQs=
  file_glob: true
  file: wheelhouse/*
  skip_cleanup: true
  on:
    repo: griels/couchbase-python-client-ng
    all_branches: true