notifications:
  email: ellis.breen@couchbase.com
matrix:
  include:
# disabled for now as dep issues
#  - sudo: required
#    services:
#    - docker
#    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
#  - sudo: required
#    services:
#    - docker
#    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64 PLAT=manylinux2014_x86_64

install:
- docker pull $DOCKER_IMAGE
script:
- ls -alrt
- chmod ugo+x travis/build-wheels.sh
- docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- echo `ls wheelhouse/`
- echo `ls /io/wheelhouse`
- echo `ls .`
- echo `ls /`
- echo `ls /io`
deploy:
  provider: releases
  api_key:
    secure: ${PYCBC_TRAVIS_API}
  file_glob: true
  file: wheelhouse/*
  skip_cleanup: true
  on:
    repo: griels/couchbase-python-client-ng
    all_branches: true
