notifications:
  email: ellis.breen@couchbase.com
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686
#  - sudo: required
#    services:
#    - docker
#    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
install:
- docker pull $DOCKER_IMAGE
script:
- ls -alrt
- chmod ugo+x travis/build-wheels.sh
- docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- echo `ls wheelhouse/`
- echo `ls /io/wheelhouse`
- echo `ls .`
- echo `ls /`
deploy:
  provider: releases
  api_key:
    secure: XN19NDbcyXNgenP8uZae1/iNN+B9zJxzD4EUPnT4w49UfGn46sfqfoVAngvUvqZt+jTjKMKgbZkZULbKWmi+V96SW6y1WcdJXgYC+f0DVI3u5NDwB0JTghbp0ovYRqJw8rzen1e2tNmhyqk5GplFLty7SjzdcjD4ND0QCz2MepUufNU0x9r0BbwBrENvTKYuZH/XNOmuWzX0dtQvFnBwX99EPF5S7PARla366khUmyT9t3vXUblnqfSKsqbrX2F+2nJi9J1fSCRr+inq8Dk50gqEIlOMccQTfoxlmpeU8o/y+D1SleenZbhYRrVId96tdLQ2iXDudZITN/iiuM70lq9UdGuCDJz0tziUJq7KUQmUBoiI/1c5QZDEtbmXcKRxhGgOSqzIpacMZRKSGqnOIL6VREawRp91VJsect2Ym3I58xoU3D5B0Nqex0lbQJBwa+ztV0Zz35UOaHYlhPhybVTswZo1f4oZX40MmoX/asSw105kzJO+mMwthfoDVa5lb+1LEBzgWZXtEUW79oG36OxXMT7eBbt6wd28om1LQKr5sU80l9kJWDIyHftPG4BylYtdAigi16nAFJ0u0rfPmUZnZ2I53d2QmMGL2rf0wcEi4hlPNo1HRyxKpwY1LHZmzx9LZmFld05V7cde05/zhagZsqh8um1j69ueXYnPvDo=
  file_glob: true
  file: wheelhouse/*
  skip_cleanup: true
  on:
    repo: griels/couchbase-python-client-ng
    all_branches: true
