# This file automatically generated by
#    /Users/ellis_breen/root/workspaces/couchbase/couchbase-python-client-clion/couchbase_version.py
# at
#    2019-06-29 11:36:41.299935
__version__ = '3.0.0a2.dev10+g7a19458'